tab_title_separator: "｜"
git
navbar:
  blog_title: 小威的漂流手札
  ground_glass:
    enable: true
    px: 4
    alpha: 0.7
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill", name: "網誌" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

index:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1
  slogan:
    text: "面對前方未知的旅途，讓我們一起開始冒險吧"

post:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1
  meta:     # 文章訊息
    date:   # 文章日期
      enable: true
      format: "LL HH:mm"    # Ref: http://momentjs.cn/docs/#/parsing/string-format/
    views:  # 瀏覽統計
      enable: true
      source: "busuanzi"    # Options: busuanzi | leancloud
  updated:  # 更新時間
    enable: true
    date_format: "LL HH:mm" # Ref: http://momentjs.cn/docs/#/parsing/string-format/
    relative: false         # 以相對時間顯示
    note_class: info        # Options: default | primary | info | success | warning | danger | light

archive:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1

category:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1

tag:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1

about:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1

  avatar: /img/avatar/avatar1.jpg
  name: 小威
  intro: 我是小威
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/weijhih1226/', tip: 'GitHub' }
    - { class: 'iconfont icon-facebook-fill', link: 'https://www.facebook.com/charlie841226/', tip: 'Facebook' }
    - { class: 'iconfont icon-instagram-fill', link: 'https://www.instagram.com/chen_weijhih/',  tip: 'Instagram' }
    - { class: 'iconfont icon-youtube-fill', link: 'https://www.youtube.com/c/%E9%99%B3%E5%A8%81%E5%BF%971',  tip: 'YouTube' }
    - { class: 'iconfont icon-linkedin-fill', link: 'https://www.linkedin.com/in/%E9%99%B3%E5%A8%81%E5%BF%97/',  tip: 'LinkedIn' }
    - { class: 'iconfont icon-line-fill', qrcode: '/img/icon/LINE QRcode.jpg' }
    - { class: 'iconfont icon-mail', link: 'mailto:cwj@cwb.gov.tw', tip: 'E-mail' }

page:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1

page404:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1

links:
  banner_img: /img/bg/background.jpg
  banner_mask_alpha: 0.1